In [47]:
import numpy as np
import pandas as pd

In [48]:
np.random.seed(1)
x = np.random.randn(2,3)
print(x)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]


In [49]:
def sigmoid(z):
    s =1/1+np.exp(-z)
    return s

In [50]:
s = sigmoid(x)
print(s)

[[ 1.19704062  2.8436668   2.69582908]
 [ 3.92404702  1.42087995 10.98954151]]


In [51]:
def tan(z):
    s = (np.exp(z)-np.exp(-z))/(np.exp(z)+np.exp(-z))
    return s

In [52]:
t = tan(x)
print(t)

[[ 0.92525207 -0.5453623  -0.48398233]
 [-0.79057703  0.69903334 -0.98015695]]


In [53]:
np.random.seed(1)
x = np.random.randn(2,3)
y = (np.random.randn(1,3)>0)

In [54]:
print(x)
print(x.shape)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]
(2, 3)


In [55]:
print(y)

[[ True False  True]]


In [56]:
def layer_sizes(x, y,layers):
    n_x = x.shape[0]
    n_h = layers
    n_y = y.shape[0]
    return (n_x, n_h, n_y)

In [57]:
n_x, n_h, n_y = layer_sizes(x,y,4)

In [58]:
print(n_x, n_h, n_y)

2 4 1
