In [24]:
# Logistic regression gadient descent through metrix
import numpy as np


In [25]:
def sigmoid(z):
    s = 1/(1 + np.exp(-z))
    return s

In [26]:
x = np.array([[1.,2.,-1.],[3.,4.,-3.2]])
y = np.array([[1,0,1]])
x = x.T
y = y.T
w = np.array([[1.2],[2.3]])
print(w.shape)
b = 2
nx = 2
m = 3
h = np.dot(x,w) + b
a = sigmoid(h)
error = a-y
cost = -(np.sum(y * np.log(a) + (1-y)* (np.log(1-a))))/m
dw = np.dot(x.T, error) / m
db = np.sum(a-y) / m
lr = 0.09
w = w - lr * dw
b = b - lr * db
print(w,b,h)

(2, 1)
[[1.11004372]
 [2.08413958]] 1.9999588530364654 [[10.1 ]
 [13.6 ]
 [-6.56]]


In [33]:
def LGD(x,y,lr,epoch):
    x = x
    y = y
    x = x.T
    y = y.T
    b = 0
    nx = x.shape[1]  # Number of features
    m = x.shape[0]  # Number of traning samples
    w = np.random.rand(nx,1)
    cost = []  # STores ow value changes, should decrease
    for i in range(epoch):
        h = np.dot(x,w) + b
        a = sigmoid(h)
        a = np.clip(a,1e-15,1-1e-15)
        error = a-y
        cost1 = -(np.sum(y * np.log(a) + (1-y)* (np.log(1-a))))/m
        if i % 1000 == 0:
            print(cost1)
        cost.append(cost1)
        dw = np.dot(x.T, error) / m
        db = np.sum(error) / m
        w = w - lr * dw
        b = b - lr * db
    return(w,b)

In [39]:
x = np.array([[1.,2.,-1.],[3.,4.,-3.2]])
y = np.array([[1,0,1]])
LGD(x,y,0.01,10000)

2.93621709831957
0.11355183953935792
0.06034792126529572
0.040510886361907895
0.03033719775138127
0.024192588184665298
0.02009329873791865
0.01716942722124519
0.014981388784158084
0.013283770938739883


(array([[-10.05726597],
        [  2.00112081]]),
 np.float64(7.916123350757799))

In [40]:
import numpy as np
import sklearn.linear_model as lm

x = np.array([[1.,2.,-1.],[3.,4.,-3.2]]).T
y = np.array([1,0,1])

lg = lm.LogisticRegression()

lg.fit(x, y)

print(lg.intercept_)
print(lg.coef_)
print(w,b)

[2.33947315]
[[-0.4227781  -0.47915636]]
[[1.11004372]
 [2.08413958]] 1.9999588530364654


In [41]:
x = np.array([[1.,3.],[2.,4.],[-1.,-3.2]])
y = np.array([[1],[0],[1]])
LGD(x,y,0.01,10000)

2.5093666210729015
0.04385247808370776
0.02296248044323821
0.015559027779183176
0.011765577697861516
0.009458994875656762
0.00790833280494058
0.006794326815773631
0.005955316438428235
0.005300674595739626


(array([[ 1.08248067, -0.91213443,  1.08248067],
        [ 2.23121955, -1.47624336,  2.23121955],
        [-0.07892256,  1.94386928, -0.07892256]]),
 np.float64(0.20875738785776826))