In [ ]:
import numpy as np
import pandas as pd
# dont put sigmoid in the hidden layer

In [212]:
np.random.seed(1)
x = np.random.randn(2,3)
print(x)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]


In [213]:
def sigmoid(z):
    s =1/(1+np.exp(-z))
    return s

In [214]:
s = sigmoid(x)
print(s)

[[0.83539354 0.35165864 0.3709434 ]
 [0.25483894 0.70378922 0.09099561]]


In [215]:
def tan(z):
    s = (np.exp(z)-np.exp(-z))/(np.exp(z)+np.exp(-z))
    return s

In [216]:
t = tan(x)
print(t)

[[ 0.92525207 -0.5453623  -0.48398233]
 [-0.79057703  0.69903334 -0.98015695]]


In [217]:
np.random.seed(1)
x = np.random.randn(2,3)
y = (np.random.randn(1,3)>0)

In [218]:
print(x)
print(x.shape)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]
(2, 3)


In [219]:
print(y)

[[ True False  True]]


In [220]:
def layer_sizes(x, y,layers):
    n_x = x.shape[0]
    n_h = layers
    n_y = y.shape[0]
    return (n_x, n_h, n_y)

In [221]:
n_x, n_h, n_y = layer_sizes(x,y,4)

In [222]:
print(n_x, n_h, n_y)

2 4 1


In [223]:
def initialize_parameters(n_x, n_h, n_y):
    np.random.seed(2)
    W1 = np.random.randn(n_h,n_x)*0.01
    b1 = np.zeros((n_h,1))
    W2 = np.random.randn(n_y,n_h)*0.01
    b2 = np.zeros((n_y,1))
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [224]:
p = initialize_parameters(n_x, n_h, n_y)

In [225]:
p

{'W1': array([[-0.00416758, -0.00056267],
        [-0.02136196,  0.01640271],
        [-0.01793436, -0.00841747],
        [ 0.00502881, -0.01245288]]),
 'b1': array([[0.],
        [0.],
        [0.],
        [0.]]),
 'W2': array([[-0.01057952, -0.00909008,  0.00551454,  0.02292208]]),
 'b2': array([[0.]])}

In [226]:
def forward_propogation(x,p):
    W1 = p["W1"]
    b1 = p["b1"]
    W2 = p["W2"]
    b2 = p["b2"]
    
    Z1 = np.dot(W1,x)+b1
    A1 = tan(Z1)
    Z2 = np.dot(W2,A1)+b2
    A2 = sigmoid(Z2)
    
    cache = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2}
    
    return A2, cache

In [227]:
A2, cache = forward_propogation(x,p)

In [228]:
A2

array([[0.5002307 , 0.49985831, 0.50023963]])

In [229]:
cache

{'Z1': array([[-0.00616586,  0.00206261,  0.0034962 ],
        [-0.05229879,  0.02726335, -0.02646868],
        [-0.0200999 ,  0.00368691,  0.02884556],
        [ 0.02153008, -0.01385323,  0.02600471]]),
 'A1': array([[-0.00616578,  0.0020626 ,  0.00349619],
        [-0.05225116,  0.02725659, -0.0264625 ],
        [-0.0200972 ,  0.00368689,  0.02883756],
        [ 0.02152676, -0.01385234,  0.02599885]]),
 'Z2': array([[ 0.00092281, -0.00056678,  0.00095853]]),
 'A2': array([[0.5002307 , 0.49985831, 0.50023963]])}

In [230]:
def compute_cost(A2,y,p):
    m = y.shape[1]
    logprobs = np.multiply(np.log(A2),y)+np.multiply(np.log(1-A2),(1-y))
    cost = -np.sum(logprobs)/m
    
    cost = float(np.squeeze(cost))
    
    return cost

In [231]:
compute_cost(A2,y,p)

0.6927392477233995

Do forward propogation with 5 inputs with samples and 3 layers with 4 neurons in the first layer 2 in the second and 1 in the last

In [232]:
np.random.seed(3)
x = np.random.randn(3,5)
print(x)

[[ 1.78862847  0.43650985  0.09649747 -1.8634927  -0.2773882 ]
 [-0.35475898 -0.08274148 -0.62700068 -0.04381817 -0.47721803]
 [-1.31386475  0.88462238  0.88131804  1.70957306  0.05003364]]


In [238]:
np.random.seed(1)
x = np.random.randn(5,3)
y = (np.random.randn(1,3)>0)

In [242]:
print(x.shape,x)
print()
print(y)

(5, 3) [[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]
 [-0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944]]

[[False False False]]


In [240]:
n_x, n_h, n_y = layer_sizes(x,y,4)

In [241]:
print(n_x, n_h, n_y)

5 4 1
