In [73]:
import numpy as np
import pandas as pd

In [74]:
np.random.seed(1)
x = np.random.randn(2,3)
print(x)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]


In [75]:
def sigmoid(z):
    s =1/1+np.exp(-z)
    return s

In [76]:
s = sigmoid(x)
print(s)

[[ 1.19704062  2.8436668   2.69582908]
 [ 3.92404702  1.42087995 10.98954151]]


In [77]:
def tan(z):
    s = (np.exp(z)-np.exp(-z))/(np.exp(z)+np.exp(-z))
    return s

In [78]:
t = tan(x)
print(t)

[[ 0.92525207 -0.5453623  -0.48398233]
 [-0.79057703  0.69903334 -0.98015695]]


In [79]:
np.random.seed(1)
x = np.random.randn(2,3)
y = (np.random.randn(1,3)>0)

In [80]:
print(x)
print(x.shape)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]
(2, 3)


In [81]:
print(y)

[[ True False  True]]


In [82]:
def layer_sizes(x, y,layers):
    n_x = x.shape[0]
    n_h = layers
    n_y = y.shape[0]
    return (n_x, n_h, n_y)

In [83]:
n_x, n_h, n_y = layer_sizes(x,y,4)

In [84]:
print(n_x, n_h, n_y)

2 4 1


In [85]:
def initialize_parameters(n_x, n_h, n_y):
    np.random.seed(2)
    W1 = np.random.randn(n_h,n_x)*0.01
    b1 = np.zeros((n_h,1))
    W2 = np.random.randn(n_y,n_h)*0.01
    b2 = np.zeros((n_y,1))
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [86]:
p = initialize_parameters(n_x, n_h, n_y)

In [87]:
p

{'W1': array([[-0.00416758, -0.00056267],
        [-0.02136196,  0.01640271],
        [-0.01793436, -0.00841747],
        [ 0.00502881, -0.01245288]]),
 'b1': array([[0.],
        [0.],
        [0.],
        [0.]]),
 'W2': array([[-0.01057952, -0.00909008,  0.00551454,  0.02292208]]),
 'b2': array([[0.]])}

In [ ]:
def forward_propogation(x,p):
    W1 = p["W1"]
    b1 = p["b1"]
    W2 = p["W2"]
    b2 = p["b2"]
    
    Z1 = np.dot(W1,x)+b1
    A1 = tan(Z1)
    Z2 = np.dot(W2,A1)+b2
    A2 = sigmoid(Z2)
    
    cache = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2}
    
    return A2, cache